// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC1155Supply$Type } from "./ERC1155Supply";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1155Supply"]: ERC1155Supply$Type;
    ["@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Supply.sol:ERC1155Supply"]: ERC1155Supply$Type;
  }
}
