// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SignatureChecker$Type } from "./SignatureChecker";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SignatureChecker"]: SignatureChecker$Type;
    ["@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol:SignatureChecker"]: SignatureChecker$Type;
  }
}
