// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Eip712$Type } from "./Eip712";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Eip712"]: Eip712$Type;
    ["contracts/Eip712.sol:Eip712"]: Eip712$Type;
  }
}
