// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MessageHashUtils$Type } from "./MessageHashUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MessageHashUtils"]: MessageHashUtils$Type;
    ["@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol:MessageHashUtils"]: MessageHashUtils$Type;
  }
}
