// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC5267$Type } from "./IERC5267";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC5267"]: IERC5267$Type;
    ["@openzeppelin/contracts/interfaces/IERC5267.sol:IERC5267"]: IERC5267$Type;
  }
}
